### ISSUE TITLE
build warning

### ISSUE THREAD

**Issue by guruma** [replikativ/kabel#4]
Below are error messages when i run 'lein cljsbuild once':

```
Compiling "resources/public/js/client.js" from ["src"]...
WARNING: Use of undeclared Var taoensso.timbre/-log! at line 19 src/kabel/middleware/block_detector.cljc
WARNING: Use of undeclared Var taoensso.timbre/*config* at line 19 src/kabel/middleware/block_detector.cljc
WARNING: Use of undeclared Var taoensso.timbre/-log! at line 28 src/kabel/middleware/block_detector.cljc
WARNING: Use of undeclared Var taoensso.timbre/*config* at line 28 src/kabel/middleware/block_detector.cljc
```

The bug is resolved by my fix which is attached below as a patch. I hope it helps:

```
--- a/src/kabel/middleware/block_detector.cljc
+++ b/src/kabel/middleware/block_detector.cljc
@@ -7,10 +7,11 @@
                              go-loop pub sub unsub close!]]
                :cljs [cljs.core.async :as async
                      :refer [<! >! timeout chan put! pub sub unsub close!]]))
-  #?(:cljs (:require-macros [cljs.core.async.macros :refer (go go-loop alt!)]
+  #?(:cljs (:require-macros [cljs.core.async.macros :refer [go go-loop alt!]]
                             [kabel.platform-log :refer [debug info warn error]])))


+#?(:cljs (enable-console-print!))
```

**Comment by whilo** [comment]
I am not sure yet how to fix that properly. It is a general problem with macro imports and the warning pops up all over the place if the timbre import has not happened yet at compile time, but it is harmless. We might port to timbre directly instead of forwarding in the future, so I leave the issue open for now. Thanks for reporting!

**Comment by guruma** [comment]
Have you ever thought about changing the definitions of log functions in platform-log from macro to just function?

**Comment by guruma** [comment]
hmm.. log as a function has a problem with the line number which is same as the line number as it is defined in all the messages.

**Comment by whilo** [comment]
Yes, exactly. That is why it is usually a macro, also in timber for instance.

**Comment by guruma** [comment]
I have digged this problem and got the below code which doesn't emit the warning messages.

```clj
(ns kabel.middleware.block-detector
  "Block detection middleware for replikativ."
  (:require [kabel.platform-log #?@(:clj [:refer [debug info warn error]]
                                    :cljs [:refer-macros [debug info warn error]])]
...
...
  #?(:cljs (:require-macros [cljs.core.async.macros :refer (go go-loop alt!)]
                            #_[kabel.platform-log :refer [debug info warn error]])))
```

I think that the reason why the compiler spits out the warnings is because when the compiler lookups the symbols on compilation time, it uses the macro namespaces for macro symbols(and macro helper funtions) and the runtime namespaces for normal symbols. Because `require-macros` loads `kabel.platform-log` as macro namespace, the compiler can't lookup the symbol `-log!` on rumtime namespaces where there is no kabel.platform-log loaded as runtime namespace.

It was helpful to read [blog1](http://nbeloglazov.com/2016/03/07/getting-started-with-self-hosted-cljs-part-2.html) and [blog2](http://blog.fikesfarm.com/posts/2016-01-05-clojurescript-macros-calling-functions.html) which show how clojurescript compiler deal with the macro namespace, though they were based on self-hosing clojurescript. The macro namespaces are dealt different from the runtime namespaces by jvm-hosting clojurescript compiler as well. Below code shows this:

```clj
;; foo/macro.cljc
(ns foo.macro)

(defn print-max* []
  #?(:clj (println "clj print max: " Double/MAX_VALUE)
     :cljs (println "cljs print max: " js/Number.MAX_VALUE)))

(defmacro print-max []
  (binding [*out* *err*]
    (print-max*))
  '(print-max*))
```
```clj
;; foo/core.cljs
(ns foo.core
  (:require [foo.macro :refer-macros [print-max]]))

(enable-console-print!)
(.write js/document "<h1>FOO</h1>")
(print-max)
```

The run of `lein cljsbuild once` commands shows the following:

```
Compiling "resources/public/js/app.js" from ["src"]...
clj print max:  1.7976931348623157E308
Successfully compiled "resources/public/js/app.js" in 0.131 seconds.
```

The run of `chrome resources/index.html` commands shows the following in the chrome console windows:

```
cljs print max:  1.7976931348623157e+308
```

You can notice that `print-max*` is compiled as clj for macro-expansion and as cljs for runtime.

**Comment by whilo** [comment]
Yes, this is right. I was aware that it came from the macro-expansion, but was not investigating it further, because I didn't want to push the burden of importing the log macros to users right away. With this require code-snippet it should be fine though. I still think we will probably use the timber macros directly in the future, as they are also cross-platform. Your way of requiring the namespace applies there the same then, so thanks :).

**Comment by whilo** [comment]
I will close the issue for now, feel free to reopen or add anything you want to add :).

**Comment by guruma** [comment]
It was my pleasure to help you and thanks for your great wonderful awesome projects. ^^;
